
var topics = [
    // Programming Languages
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "C#",
    "PHP",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "Rust",
    "TypeScript",
    "Scala",
    "Perl",
    "Haskell",
    "Objective-C",
    "Shell Scripting",
    "SQL",
    "R",
    "MATLAB",
    "Lua",
    "C",
    "Objective-C++",
    "Groovy",
    "Dart",
    "Julia",
    "Elixir",
    "Clojure",
    "Fortran",
    "Bash",
    "Assembly",
    "Rust",
    "Perl",
    "Haxe",
    "COBOL",
    "Ada",
    "Erlang",
    "Prolog",
    "OCaml",
    "Scheme",
    "F#",
    "D",
    "PowerShell",
    "PL/SQL",
    "Tcl",
    "VB.NET",
    
    // Web Development Frameworks
    "Django",
    "Flask",
    "Ruby on Rails",
    "ASP.NET",
    "Express.js",
    "Vue.js",
    "React.js",
    "AngularJS",
    "Ember.js",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "Spring",
    "ASP.NET Core",
    "NestJS",
    "AdonisJS",
    "Ruby on Rails",
    "Next.js",
    "Gatsby",
    "Svelte",
    "AdonisJS",
    "Django REST framework",
    "Fastify",
    "Rocket",
    "Symfony",
    "CakePHP",
    "Zend Framework",

    // Front-end Development Libraries
    "jQuery",
    "Sass",
    "Less",
    "Bootstrap",
    "Tailwind CSS",
    "Emotion",
    "Chakra UI",
    "Ant Design",
    "Bulma",
    "Foundation",
    
    // Back-end Development Frameworks
    "Express.js",
    "Koa",
    "FastAPI",
    "Gin",
    "Flask",
    "Deno",
    "Actix",
    "Rocket",
    "Django",
    "Ruby on Rails",
    "Lumen",
    
    // Mobile App Development Frameworks
    "React Native",
    "Flutter",
    "Ionic",
    "Xamarin",
    "NativeScript",
    "PhoneGap",
    "Corona SDK",
    "Kivy",
    "Adobe PhoneGap",
    "Quasar",
    "Onsen UI",
    "React Native Windows",
    
    // Game Development Frameworks
    "Unity",
    "Unreal Engine",
    "Cocos2d",
    "Godot",
    "Phaser",
    "LÖVE",
    "Panda3D",
    "GDevelop",
    "Phaser",
    "Superpowers",
    
    // Machine Learning and Data Science Libraries
    "TensorFlow",
    "PyTorch",
    "scikit-learn",
    "Keras",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "NLTK",
    "OpenCV",
    "Spark",
    "Hadoop",
    "CNTK",
    "Theano",
    "MXNet",
    "H2O",
    "Caffe",
    "Apache Flink",
    "AutoML",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "DataRobot",
    "PyCaret",
    "RAPIDS",
    
    // Cloud Platforms and Tools
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "Firebase",
    "Docker",
    "Kubernetes",
    "Ansible",
    "Heroku",
    "DigitalOcean",
    "Alibaba Cloud",
    "IBM Cloud",
    "Terraform",
    "Oracle Cloud",
    "OpenStack",
    "Cloud Foundry",
    "HashiCorp Vault",

    // Database Technologies
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Cassandra",
    "Elasticsearch",
    "SQLite",
    "MariaDB",
    "Amazon Redshift",
    "Neo4j",
    "InfluxDB",
    "Apache Cassandra",
    "ArangoDB",
    
    // Testing Frameworks
    "JUnit",
    "Pytest",
    "Mocha",
    "RSpec",
    "JUnit",
    "Selenium",
    "Cypress",
    "TestNG",
    "Jasmine",
    "PHPUnit",
    "TestCafe",
    "Mockito",
    
    // Other Technologies and Concepts
    "DevOps",
    "CI/CD",
    "Microservices",
    "Serverless Architecture",
    "API Development",
    "Blockchain",
    "Cybersecurity",
    "Internet of Things (IoT)",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Data Visualization",
    "Big Data",
    "Chatbot Development",
    "Automation Testing",
    "Open Source Software",
    "GraphQL",
    "OAuth",
    "JSON Web Tokens (JWT)",
    "Apache Kafka",
    "RabbitMQ",
    "MicroPython",
    "Serverless Framework",
    "Natural Language Processing (NLP)",
    "Robotic Process Automation (RPA)",
    "Low-Code Development",
    "No-Code Development",
    "Progressive Web Apps (PWA)",
    "Containerization",
    "Graph Databases",
    "ARCore",
    "ARKit",
    "Unity ML-Agents",
    "ARFoundation",
    "Kotlin Multiplatform",
    "WebAssembly",
    "Docker Compose",
    "Kubernetes Operators",
    "Knative",
    "Apache Beam",
    "Apache Airflow",
    "ETL (Extract, Transform, Load)",
    "Low-Code Platforms",
    "BigQuery",
    "Firebase ML",
    "Twilio",
    "Digital Twins",
    "Serverless Computing",
];

